# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CacheDeviceInventory',
            fields=[
                ('ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=200)),
                ('visible_hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('ts_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'cache_device_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CacheKelasPengajar',
            fields=[
                ('kd_kelas', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nip_dosen', models.CharField(max_length=200)),
                ('nama_dosen', models.CharField(max_length=1000)),
                ('bobot', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('ts_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'cache_kelas_pengajar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CacheKelasSesiPerkuliahanDosenPengajar',
            fields=[
                ('id_kuliah', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=200)),
                ('nama_dosen', models.CharField(max_length=200)),
                ('nama_dosen_dengan_gelar', models.CharField(max_length=300)),
                ('ldap_acc', models.CharField(max_length=200)),
                ('ts_update', models.DateTimeField()),
                ('ts_last_sync_with_siak', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cache_kelas_sesi_perkuliahan_dosen_pengajar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CacheKelasSesiPerkuliahanMahasiswaPeserta',
            fields=[
                ('id_kuliah', models.BigIntegerField(primary_key=True, serialize=False)),
                ('npm', models.CharField(max_length=200)),
                ('kd_org', models.CharField(max_length=200)),
                ('ts_update', models.DateTimeField()),
                ('status_presensi', models.IntegerField()),
                ('ts_last_sync_with_siak', models.DateTimeField(blank=True, null=True)),
                ('nama_mahasiswa', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cache_kelas_sesi_perkuliahan_mahasiswa_peserta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CacheRfidTagNoIdentitas',
            fields=[
                ('rfid_tag', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kode_identitas', models.CharField(max_length=100)),
                ('kode_organisasi', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cache_rfid_tag_no_identitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoveryKelasSesiPerkuliahanDevice',
            fields=[
                ('id_kuliah', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=100)),
                ('catatan', models.CharField(blank=True, max_length=200, null=True)),
                ('ts_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'discovery_kelas_sesi_perkuliahan_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoveryKelasSesiPerkuliahanDosenPengajar',
            fields=[
                ('id_kuliah', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nip', models.CharField(max_length=200)),
                ('ts_presensi_device', models.DateTimeField()),
                ('mac_address_device', models.CharField(max_length=200)),
                ('ts_update', models.DateTimeField()),
                ('sudah_sync_ke_siak', models.BooleanField()),
                ('ts_sync_ke_siak', models.DateTimeField()),
            ],
            options={
                'db_table': 'discovery_kelas_sesi_perkuliahan_dosen_pengajar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiscoveryKelasSesiPerkuliahanMahasiswaPeserta',
            fields=[
                ('id_kuliah', models.BigIntegerField(primary_key=True, serialize=False)),
                ('npm', models.CharField(max_length=200)),
                ('kd_org', models.CharField(max_length=200)),
                ('ts_presensi_device', models.DateTimeField()),
                ('mac_address_device', models.CharField(max_length=200)),
                ('ts_update', models.DateTimeField()),
                ('sudah_sync_ke_siak', models.BooleanField()),
                ('ts_sync_ke_siak', models.DateTimeField()),
            ],
            options={
                'db_table': 'discovery_kelas_sesi_perkuliahan_mahasiswa_peserta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KonfigurasiKelasJadwalRutin',
            fields=[
                ('kd_kelas', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hari_ke', models.IntegerField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('tgl_mulai_otomatis_buat_jadwal', models.DateTimeField()),
                ('tgl_berakhir_otomatis_buat_jadwal', models.DateTimeField()),
                ('aktif', models.BooleanField()),
                ('kd_mk', models.CharField(blank=True, max_length=500, null=True)),
                ('nama_mk', models.CharField(blank=True, max_length=500, null=True)),
                ('nama_kelas', models.CharField(blank=True, max_length=500, null=True)),
                ('nama_hari', models.CharField(blank=True, max_length=500, null=True)),
                ('ts_update', models.DateTimeField()),
                ('kd_org', models.CharField(blank=True, max_length=200, null=True)),
                ('thn', models.IntegerField(blank=True, null=True)),
                ('term', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'konfigurasi_kelas_jadwal_rutin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KonfigurasiPengecualianJadwalRutin',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipe', models.CharField(max_length=200)),
                ('kd_org', models.CharField(blank=True, max_length=200, null=True)),
                ('kd_kelas', models.CharField(blank=True, max_length=200, null=True)),
                ('tgl_pengecualian', models.DateField()),
                ('operator', models.CharField(blank=True, max_length=500, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'konfigurasi_pengecualian_jadwal_rutin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmpEuisJadwalKuliah',
            fields=[
                ('id_kuliah', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('mac_address', models.CharField(blank=True, max_length=200, null=True)),
                ('wkt_mulai', models.DateTimeField(blank=True, null=True)),
                ('wkt_selesai', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tmp_euis_jadwal_kuliah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmpEuisPeserta',
            fields=[
                ('id_kuliah', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('no_identitas', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tmp_euis_peserta',
                'managed': False,
            },
        ),
    ]
